server.port=8084
spring.application.name=ms-asistencia

spring.cloud.compatibility-verifier.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/db_asistencia
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

ms.estudiantes.url=http://localhost:8081
ms.curso.url=http://localhost:8082